# Generated by Django 5.2.5 on 2025-08-31 14:45

from django.db import migrations

def forwards_func(apps, schema_editor):
    School = apps.get_model("registration", "School")
    db_alias = schema_editor.connection.alias

    # Add some random school names
    random_schools = [
        "St. Joseph Higher Secondary School",
        "Notre Dame College",
        "Viqarunnisa Noon School and College",
        "Ideal School and College",
        "Dhaka Residential Model College",
    ]
    for name in random_schools:
        School.objects.using(db_alias).get_or_create(name=name)


def reverse_func(apps, schema_editor):
    # This is a one-way data migration.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]