# Generated by Django 5.2.5 on 2025-10-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_studenteventregistration_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reference',
            field=models.CharField(blank=True, help_text="Campus Ambassador's name", max_length=200, null=True),
        ),
    ]
