# Generated by Django 5.2.5 on 2025-09-03 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_add_random_schools'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('TEAM', 'Team')], default='INDIVIDUAL', help_text="Select 'Team' for team-based events.", max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='max_team_size',
            field=models.PositiveIntegerField(blank=True, help_text="Required if event type is 'Team'. Minimum 2 members.", null=True, validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Keep blank for unlimited participants.', null=True),
        ),
    ]
