# Generated by Django 5.2.5 on 2025-09-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_team_studenteventregistration_team_teammember'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='student',
        ),
    ]
