# Generated by Django 5.2.5 on 2025-09-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_countdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
