# Generated by Django 5.2.5 on 2025-09-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_homepageasset_socialmediaprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='rules_file',
            field=models.FileField(blank=True, null=True, upload_to='event_rules/'),
        ),
        migrations.AddField(
            model_name='event',
            name='rules_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='rules_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('PDF', 'PDF')], default='TEXT', max_length=10),
        ),
    ]
