# Generated by Django 5.2.5 on 2025-09-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_event_event_image_event_rules_file_event_rules_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastEventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='past_events/')),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='team_members/')),
                ('member_type', models.CharField(choices=[('MODERATOR', 'Moderator'), ('BOARD_MEMBER', 'Board Member')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='socialmediaprofile',
            name='platform',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('TWITTER', 'Twitter'), ('LINKEDIN', 'LinkedIn'), ('YOUTUBE', 'YouTube'), ('DISCORD', 'Discord')], max_length=20, unique=True),
        ),
    ]
