# Generated by Django 5.2.5 on 2025-09-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_valorantbackgroundvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.FileField(upload_to='site_logos/')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
