# Generated by Django 5.2.5 on 2025-09-14 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_sitelogo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
    ]
